#!/bin/sh

# run /init-s6 with PID 1, creating a new PID namespace if necessary
if [ "$$" -eq 1 ]; then
    # we already have PID 1
    exec /init-s6 "$@"
else
    # create a new PID namespace
    exec unshare -r --pid sh -c '
        # set up /proc and start the real init in the background
        unshare --mount-proc /init-s6 "$@" &
        child="$!"
        # forward signals to the real init
        trap "kill -INT \$child" INT
        trap "kill -TERM \$child" TERM
        # wait until the real init exits
        # ("wait" returns early on signals; "kill -0" checks if the process exists)
        until wait "$child" || ! kill -0 "$child" 2>/dev/null; do :; done
    ' sh "$@"
fi
